name: youcanpay_sdk
description: YouCanPay Flutter SDK makes it quick and easy to build an excellent payment experience in your Android & iOS apps with YouCan Pay API. We provide powerful and customizable UI screens to make your payment more easier
version: 0.0.2
homepage: https://youcanpay.com/
repository: https://github.com/youcan-shop/youcan-pay-flutter-sdk
issue_tracker: https://github.com/youcan-shop/youcan-pay-flutter-sdk/issues

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
